version: "3.8"

services:
  web:
    build: .
    container_name: test03_web
    restart: always
    environment:
      DATABASE_URL: "sqlite3:///app/storage/development.sqlite3"
      BUNDLE_PATH: /app/vendor/bundle # 追加！
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_data:/app/vendor/bundle # 追加！
    stdin_open: true
    tty: true

volumes:
  bundle_data:
