services:
  web:
    build: .
    container_name: test03_web
    restart: no
    environment:
      DATABASE_URL: "sqlite:///app/db/development.sqlite3"
      BUNDLE_PATH: /app/vendor/bundle # 追加！
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_data:/app/vendor/bundle # 追加！
    stdin_open: true
    tty: true
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle install && rails server -b 0.0.0.0"

volumes:
  bundle_data:
